language: cpp
sudo: false
compiler:
  - gcc
  - clang
before_script:
  - bash ./scripts/check-whitespace.sh
  - mkdir ../build
  - cd ../build
script:
  - cmake ../mp2-full-sources
  - make -j
  - cd ./bin/
  - ./test_set
notifications:
  email: false
